### ISSUE TITLE
fut C++ build warnings

### ISSUE THREAD

**Issue by iahung2** [fusionlanguage/fut#96]
This will get rid of these warnings:

```
libfut.cpp: In member function 'std::shared_ptr<FuExpr> FuSema::visitInterpolatedString(std::shared_ptr<FuInterpolatedString>)':
libfut.cpp:4055:45: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<FuInterpolatedPart>::size_type' {aka 'long long unsigned int'} [-Wsign-compare]
 4055 |         for (int partsIndex = 0; partsIndex < expr->parts.size(); partsIndex++) {
      |                                  ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
libfut.cpp: In member function 'std::shared_ptr<FuExpr> FuSema::resolveCallWithArguments(std::shared_ptr<FuCallExpr>, const std::vector<std::shared_ptr<FuExpr> >*)':
libfut.cpp:5282:23: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<std::shared_ptr<FuExpr> >::size_type' {aka 'long long unsigned int'} [-Wsign-compare]
 5282 |                 if (i >= arguments->size()) {
      |                     ~~^~~~~~~~~~~~~~~~~~~~
libfut.cpp:5299:15: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<std::shared_ptr<FuExpr> >::size_type' {aka 'long long unsigned int'} [-Wsign-compare]
 5299 |         if (i < arguments->size())
      |             ~~^~~~~~~~~~~~~~~~~~~
libfut.cpp:5313:31: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<std::shared_ptr<FuExpr> >::size_type' {aka 'long long unsigned int'} [-Wsign-compare]
 5313 |                         if (i < arguments->size())
      |                             ~~^~~~~~~~~~~~~~~~~~~
libfut.cpp: In member function 'std::shared_ptr<FuExpr> FuSema::visitCallExpr(std::shared_ptr<FuCallExpr>)':
libfut.cpp:5342:35: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<std::shared_ptr<FuExpr> >::size_type' {aka 'long long unsigned int'} [-Wsign-compare]
 5342 |                 for (int i = 0; i < arguments->size(); i++) {
      |                                 ~~^~~~~~~~~~~~~~~~~~~
libfut.cpp: In member function 'std::shared_ptr<FuExpr> FuSema::visitExpr(std::shared_ptr<FuExpr>)':
libfut.cpp:5400:35: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<std::shared_ptr<FuExpr> >::size_type' {aka 'long long unsigned int'} [-Wsign-compare]
 5400 |                 for (int i = 0; i < items->size(); i++)
      |                                 ~~^~~~~~~~~~~~~~~
libfut.cpp: In member function 'void FuSema::visitSwitch(FuSwitch*)':
libfut.cpp:5834:35: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<std::shared_ptr<FuExpr> >::size_type' {aka 'long long unsigned int'} [-Wsign-compare]
 5834 |                 for (int i = 0; i < kase.values.size(); i++) {
      |                                 ~~^~~~~~~~~~~~~~~~~~~~
libfut.cpp: In member function 'void GenBase::writeCoercedLiterals(const FuType*, const std::vector<std::shared_ptr<FuExpr> >*)':
libfut.cpp:6834:27: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<std::shared_ptr<FuExpr> >::size_type' {aka 'long long unsigned int'} [-Wsign-compare]
 6834 |         for (int i = 0; i < exprs->size(); i++) {
      |                         ~~^~~~~~~~~~~~~~~
libfut.cpp: In member function 'void GenC::writeArgsAndRightParenthesis(const FuMethod*, const std::vector<std::shared_ptr<FuExpr> >*)':
libfut.cpp:10158:23: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<std::shared_ptr<FuExpr> >::size_type' {aka 'long long unsigned int'} [-Wsign-compare]
10158 |                 if (i >= args->size())
      |                     ~~^~~~~~~~~~~~~~~
libfut.cpp: In member function 'void GenD::writeInsertedArg(const FuType*, const std::vector<std::shared_ptr<FuExpr> >*, int)':
libfut.cpp:15660:26: warning: comparison of integer expressions of different signedness: 'std::vector<std::shared_ptr<FuExpr> >::size_type' {aka 'long long unsigned int'} and 'int' [-Wsign-compare]
15660 |         if (args->size() <= index) {
      |             ~~~~~~~~~~~~~^~~~~~~~
libfut.cpp: In member function 'void GenJsNoModule::writeInterpolatedLiteral(std::string_view)':
libfut.cpp:17904:48: warning: comparison of integer expressions of different signedness: 'int' and 'std::basic_string_view<char>::size_type' {aka 'long long unsigned int'} [-Wsign-compare]
17904 |                 if (c == '`' || (c == '$' && i < s.length() && s[i] == '{'))
      |                                              ~~^~~~~~~~~~~~
libfut.cpp: In member function 'void GenSwift::initVarsAtIndent()':
libfut.cpp:20706:42: warning: comparison of integer expressions of different signedness: 'std::vector<std::unordered_set<std::basic_string_view<char> > >::size_type' {aka 'long long unsigned int'} and 'int' [-Wsign-compare]
20706 |         while (this->varsAtIndent.size() <= this->indent) {
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
libfut.cpp: In member function 'virtual void GenSwift::visitSwitch(const FuSwitch*)':
libfut.cpp:20972:35: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<std::shared_ptr<FuExpr> >::size_type' {aka 'long long unsigned int'} [-Wsign-compare]
20972 |                 for (int i = 0; i < kase.values.size(); i++) {
      |                                 ~~^~~~~~~~~~~~~~~~~~~~
```

**Comment by pfusik** [comment]
What do you mean by "use `size_t`" ? Introduce the `size_t` type in Fusion? Or emit type casts?

**Comment by iahung2** [comment]
> What do you mean by "use `size_t`" ? Introduce the `size_t` type in Fusion? Or emit type casts?

Use `size_t` in the generated code instead of `int`. As you can see, you are currently use `int`.

**Comment by pfusik** [comment]
Transpiling all `int`s to `size_t` is not an option. `size_t` is an unsigned type.

**Comment by iahung2** [comment]
> Transpiling all `int`s to `size_t` is not an option. `size_t` is an unsigned type.

No. I didn't tell you to replace all instances of `int` to `size_t`. But `size_t` should be used for indexes (please read the warnings I posted on this thread) and something related to size like `klass->typeParameterCount` and `arrayStg->length` on #97.

**Comment by iahung2** [comment]
Oh my bad. If the original Fusion code uses `int` then the transpiler just translated them as is. I mistakenly thought that Fusion itself is written in C++ so I raised this issue.

**Comment by iahung2** [comment]
@pfusik Which language is Fusion written in? I'm confused. Is it written in itself or in C++?

**Comment by pfusik** [comment]
Fusion is [self-hosted](https://en.wikipedia.org/wiki/Self-hosting_(compilers)). It transpiles itself to C++, C# and JavaScript.

I'd like to avoid the C++ compilation warnings, but haven't decided yet how.

**Comment by iahung2** [comment]
> Fusion is [self-hosted](https://en.wikipedia.org/wiki/Self-hosting_(compilers)). It transpiles itself to C++, C# and JavaScript.
> 
> I'd like to avoid the C++ compilation warnings, but haven't decided yet how.

Done 😄 

https://github.com/fusionlanguage/fut/pull/99

**Comment by pfusik** [comment]
I don't want to hide the warnings.

One option is emitting `std::ssize`, unfortunately that's C++20. Shall we cast to `ptrdiff_t` instead?

**Comment by BenBE** [comment]
`ssize_t` (in `stddef.h`) has been around for quite some time.

(I know that's not proper, canonical C++ in the purist sense, could use `cstddef` instead, but not sure re namespacing on those).

**Comment by pfusik** [comment]
I chose `std::ssize`. Compilers have been supporting it [for some time](https://en.cppreference.com/w/cpp/compiler_support) and `fut` requires a C++20 compiler anyway. I know many projects are still not yet on C++20, but that's only a matter of time.

What's left is string length:

    libfut.cpp: In member function 'void GenJsNoModule::writeInterpolatedLiteral(std::string_view)':
    libfut.cpp:17904:48: warning: comparison of integer expressions of different signedness: 'int' and 
     'std::basic_string_view<char>::size_type' {aka 'long long unsigned int'} [-Wsign-compare]
      17904 |                 if (c == '`' || (c == '$' && i < s.length() && s[i] == '{'))
            |                                              ~~^~~~~~~~~~~~
